<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%goods_category_attributes}}".
 *
 * @property string $id
 * @property string $category_id
 * @property string $title
 * @property string $value
 * @property string $sort
 */
class GoodsCategoryAttributes extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%goods_category_attributes}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort'], 'integer'],
            [['value'], 'string'],
            [['title'], 'string', 'max' => 255],

            [['category_id'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => '产品分类',
            'title' => '名称',
            'value' => '值',
            'sort' => '排序',
        ];
    }

    public function getCategory(){
        return $this->hasOne(GoodsCategory::className(),['id'=>'category_id']);
    }

    public function beforeSave($insert)
    {

        if(is_array($this->category_id)){
            $this->category_id=implode(',',$this->category_id);
        }


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function getCategoryValue(){
        if($this->category_id){
            $arr=explode(',',$this->category_id);
            $category=GoodsCategory::find()->where(['in','id',$arr])->all();
            $html=[];
            foreach ($category as $k=>$v){
                $html[]=$v->title;
            }
            return implode(',',$html);
        }else{
            return '';
        }

    }

}
