<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%goods}}".
 *
 * @property string $id
 * @property string $title
 * @property string $price
 * @property string $sales
 * @property integer $number
 * @property string $content
 * @property string $give_number
 */
class Goods extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%goods}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['price','money'], 'number'],
            [['sales', 'number', 'give_number'], 'integer'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['image','more_image','sort','type'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'price' => '价格',
            'sales' => '销量',
            'number' => '库存',
            'content' => '内容',
            'give_number' => '赠送产品数量',
            'image'=>'封面图',
            'more_image'=>'轮播图',
            'money'=>'推人奖',
            'sort'=>'排序'
        ];
    }

    public function beforeSave($insert)
    {
        if(is_array($this->more_image)){
            $this->more_image=implode(',',$this->more_image);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
