<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%news}}".
 *
 * @property integer $id
 * @property integer $type
 * @property string $title
 * @property integer $sort
 * @property integer $hit
 * @property integer $is_html
 * @property string $image
 * @property string $content
 * @property integer $created_at
 * @property integer $updated_at
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%news}}';
    }


//    public function behaviors()
//    {
//        return [
//            TimestampBehavior::className(),
//
//        ];
//    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'sort', 'hit', 'is_html','is_news','category_id'], 'integer'],
            [['title'], 'required'],
            [['content','language'], 'string'],
            [['title', 'image'], 'string', 'max' => 255],
            [['created_at','updated_at'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => '类型',
            'category_id'=>'分类',
            'title' => '标题',
            'sort' => '排序',
            'hit' => '点击数',
            'is_html' => '首页推荐',
            'is_news'=>'走进员工推荐',
            'image' => '图片',
            'content' => '内容',
            'created_at' => '添加时间',
            'updated_at' => '修改时间',
        ];
    }

    public function beforeSave($insert)
    {
        $this->language=Yii::$app->language;
        if($this->isNewRecord and $this->created_at==0){
            $this->created_at=time();
        }
        $this->updated_at=time();
        if(!is_numeric($this->created_at)){
            $this->created_at=strtotime($this->created_at);
        }

        if($this->title){
            $this->title2=str_replace(' ','-',strtolower($this->title));
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public static function getList($where,$limit=0,$begin=0){
        if($limit>0){
            $model=News::find()->where($where)->andWhere(['language'=>Yii::$app->language])->limit($limit)->orderBy('sort asc,created_at desc,id desc')->all();
        }else{
            $model=News::find()->where($where)->andWhere(['language'=>Yii::$app->language])->offset($begin)->orderBy('sort asc,created_at desc,id desc')->all();
        }

        return $model;
    }


    public function getCategory(){
        return $this->hasOne(NewsCategory::className(),['id'=>'category_id']);
    }
}
