<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%task}}".
 *
 * @property string $id
 * @property string $user_id
 * @property string $name
 * @property string $content
 * @property integer $type
 * @property integer $level
 * @property string $head
 * @property string $assisting
 * @property string $confirm
 * @property string $start_time
 * @property string $end_time
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $hour
 * @property integer $category
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%task}}';
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::className(),

        ];
    }

    public static $status_message=[
        1=>'未启动',
        2=>'进行中',
        3=>'待确认',
        4=>'已完成'
    ];

    public static $type_message=[
        1=>'常规工作',
        2=>'月度工作',
        3=>'年度工作'
    ];

    public static $level_message=[
        1=>'日常',
        2=>'临时',
        3=>'重要'
    ];

    public static $category_message=[
        1=>'指派',
        2=>'上报'
    ];


    public static $status_color=[
        1=>4,
        2=>1,
        3=>2,
        4=>3
    ];


    public static $type_color=[
        1=>'5',
        2=>'5-3',
        3=>'5-2',
    ];

    public static $type_color2=[
        1=>'fs12',
        2=>'fs12 red',
        3=>'fs12 yell',
    ];

    public static $level_color=[
        1=>'',
        2=>'color2',
        3=>'color1',
    ];


    public static $level_color2=[
        1=>'c4f fs12',
        2=>'c4f fs12 bordfa',
        3=>'c4f fs12 bordf',
    ];


    public static $status_color2=[
        1=>'c1c bgfa',
        2=>'c1c',
        3=>'c1c bge1',
        4=>'c1c bgf7 c99'
    ];

    public static $type_color3=[
        1=>'y_pop_personnel_10_color_1',
        2=>'y_pop_personnel_10_color_2',
        3=>'y_pop_personnel_10_color_3'
    ];
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'type', 'level', 'head', 'assisting', 'confirm', 'status', 'created_at', 'updated_at','category'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['hour'],'number'],
            [['content'], 'string', 'max' => 1000],
            [['start_time','end_time'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => '用户',
            'name' => '名称',
            'content' => '内容',
            'type' => '类型',
            'level' => '等级',
            'head' => '负责人',
            'assisting' => '协办人',
            'confirm' => '确认人',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
            'status' => '状态',
            'created_at' => '添加时间',
            'updated_at' => '修改时间',
            'hour'=>'工时',
            'category'=>'分类',
        ];
    }


    public function getUser(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }

    public function beforeSave($insert)
    {
        if(!is_numeric($this->start_time)){
            $this->start_time=strtotime($this->start_time);
        }
        if(!is_numeric($this->end_time)){
            $this->end_time=strtotime($this->end_time);
        }
        if($this->hour==0){
            $this->hour=round(($this->end_time-$this->start_time)/3600,1);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getDetail(){
        return $this->hasMany(TaskDetail::className(),['task_id'=>'id'])->orderBy('id asc');
    }

    public function getDetailHours(){
        if($this->detail){
            $model=TaskDetail::find()->where(['task_id'=>$this->id])->sum('hour')*1;
            if($model>0){
                return sprintf('%.1f',$model);
            }else{
                if($this->number==100){
                    return sprintf('%.1f',$this->hour);
                }else{
                    return 0;
                }

            }

        }else{
            if($this->number==100){
                return sprintf('%.1f',$this->hour);
            }else{
                return 0;
            }
        }
    }


    public function getBeizhu(){
        $model=TaskDetail::find()->where(['status'=>2,'task_id'=>$this->id])->one();
        if($model){
            return $model->content;
        }else{
            return '';
        }

    }

}
