<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%task_detail}}".
 *
 * @property string $id
 * @property string $user_id
 * @property string $task_id
 * @property string $content
 * @property string $number
 * @property string $start_time
 * @property string $end_time
 * @property string $hour
 * @property string $created_at
 * @property string $updated_at
 */
class TaskDetail extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%task_detail}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),

        ];
    }

    public static $status_message=[
        1=>'上报了工作进度',
        2=>'标记完成',
        3=>'确认完成'
    ];

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'task_id', 'number', 'created_at', 'updated_at'], 'integer'],
            [['hour'], 'number'],
            [['content'], 'string', 'max' => 1000],
            [['start_time','end_time'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => '用户',
            'task_id' => '任务',
            'content' => '进度内容',
            'number' => '工作进度',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
            'hour' => '所用工时',
            'created_at' => '添加时间',
            'updated_at' => '修改时间',
        ];
    }

    public function beforeSave($insert)
    {
        if(!is_numeric($this->start_time)){
            $this->start_time=strtotime($this->start_time);
        }
        if(!is_numeric($this->end_time)){
            $this->end_time=strtotime($this->end_time);
        }
        if($this->hour==0){
            $this->hour=round(($this->end_time-$this->start_time)/3600,1);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
