<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%work_log}}".
 *
 * @property string $id
 * @property string $user_id
 * @property string $content
 * @property string $created_at
 */
class WorkLog extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%work_log}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'created_at'], 'integer'],
            [['content'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => '用户',
            'content' => '内容',
            'created_at' => '添加时间',
        ];
    }


    public function beforeSave($insert)
    {
       if($this->isNewRecord){
           $this->created_at=time();
       }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getUser(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }
}
